version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: arjeo/talk-to-repo-frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: arjeo/talk-to-repo-backend
    ports:
      - '8000:8000'
    environment:
      - ALLOWED_ORIGINS=http://frontend:3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORG_ID=${OPENAI_ORG_ID}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - USE_ANTHROPIC=${USE_ANTHROPIC}
      - USE_CHROMA=${USE_CHROMA}
      - MODEL_NAME=${MODEL_NAME}
      - TEMPERATURE=${TEMPERATURE}
      - TOKEN_LIMIT=${TOKEN_LIMIT}
      - CONTEXT_NUM=${CONTEXT_NUM}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
      - PINECONE_INDEX=${PINECONE_INDEX}
      - NAMESPACE=${NAMESPACE}
      - PINECONE_PROJECT_ID=${PINECONE_PROJECT_ID}
      - CHUNK_SIZE=${CHUNK_SIZE}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP}
