version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: arjeo/talk-to-repo-frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: arjeo/talk-to-repo-backend
    ports:
      - '8000:8000'
    environment:
      - ALLOWED_ORIGINS=http://frontend:3000