name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push frontend
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: Dockerfile
        push: true
        tags: arjeo/talk-to-repo-frontend:latest

    - name: Build and push backend
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        dockerfile: ./backend/Dockerfile
        push: true
        tags: arjeo/talk-to-repo-backend:latest